# Minesweeper-RC GitLab CI script
# -------------------------------
# The script is composed of 3 stages: build, test and deploy.  
#
# The build stage restores NuGet packages and runs msbuild to build the EXE.
# The test stage runs mstest to run the tests inside the test project.
# The deploy stage copies the EXE to a specified location.

before_script:
  - FOR /f "tokens=2 delims==" %%a in ('wmic OS Get localdatetime /value') do set "dt=%%a"
  - SET "YY=%dt:~2,2%" & SET "YYYY=%dt:~0,4%" & SET "MM=%dt:~4,2%" & SET "DD=%dt:~6,2%"
  - SET "HH=%dt:~8,2%" & SET "Min=%dt:~10,2%" & SET "Sec=%dt:~12,2%"
  - SET "DATE_TIME_STAMP=%YYYY%%MM%%DD%_%HH%%Min%%Sec%"

variables:
  EXE_RELEASE_FOLDER: '.\Minesweeper RC\bin\Release'
  TEST_RELEASE_FOLDER: '.\Minesweeper RC Test\bin\Release'
  DEPLOY_ROOT_FOLDER: 'C:\Users\antho\Desktop\Minesweeper RC Releases'
  
  NUGET_PATH: 'C:\Program Files (x86)\NuGet'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin'
  MSTEST_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE'

stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - tags
    - web
  script:
    - echo "Fetching packages with NuGet..."
    - '"%NUGET_PATH%\nuget.exe" restore'
    - '"%MSBUILD_PATH%\msbuild.exe" /detailedsummary /consoleloggerparameters:Summary /maxcpucount /nologo /p:Configuration=Release /verbosity:normal'
  artifacts:
    name: "%DATE_TIME_STAMP%-%CI_COMMIT_TAG%"
    expire_in: 1 week
    untracked: true

test:
  stage: test
  only:
    - tags
    - web
  script:
    - '"%MSTEST_PATH%\mstest.exe" /testcontainer:"%TEST_RELEASE_FOLDER%\Minesweeper RC Test.dll"'
  dependencies:
    - build

deploy-tagged:
  stage: deploy
  only:
    - tags
  environment:
    name: staging
  script:
    - 'SET "TAG_FOLDER=%DEPLOY_ROOT_FOLDER%\%DATE_TIME_STAMP%-%CI_COMMIT_TAG%"'
    - 'xcopy /y "%EXE_RELEASE_FOLDER%\Minesweeper RC.exe" "%TAG_FOLDER%\"'
  dependencies:
    - build
    - test

deploy-untagged:
  stage: deploy
  only:
    - web
  environment:
    name: staging
  script:
    - 'SET COMMIT_FOLDER=%DEPLOY_ROOT_FOLDER%\%DATE_TIME_STAMP%-%CI_COMMIT_SHA%'
    - 'xcopy /y "%EXE_RELEASE_FOLDER%\Minesweeper RC.exe" "%COMMIT_FOLDER%\"'
  dependencies:
    - build
    - test
